version: '3.3'

volumes:
  prometheus-data: {}
  grafana-data: {}

services:
  backend:
    build:
      context: django_app
    ports:
      - "8000:8000"
    env_file:
      - .env
    command: python3 -m gunicorn --bind 0.0.0.0:8000 --workers 2 app.wsgi:application
    restart: unless-stopped

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
#    ports:
#      - "9090:9090"
    volumes:
      - ./infrastructure/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - ./infrastructure/prometheus/web.yml:/etc/prometheus/web.yml
      - prometheus-data:/prometheus
    restart: unless-stopped
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
      - "--web.config.file=/etc/prometheus/web.yml"

  grafana:
    image: grafana/grafana-oss:latest
    container_name: grafana
    ports:
      - "3000:3000"
    volumes:
      - grafana-data:/var/lib/grafana
    env_file:
      - .env
    restart: unless-stopped