{
 "title": "Django Prometheus",
 "description": "Django metrics dashboard for prometheus using django-prometheus metrics: https://github.com/korfuri/django-prometheus",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "service",
    "label": "Service",
    "query": {
     "query": "label_values(django_db_new_connections_total, service)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Total Requests",
   "type": "stat",
   "description": "increase(v range-vector) calculates the increase in the time series in the range vector. Breaks in monotonicity (such as counter resets due to target restarts) are automatically adjusted for. The increase is extrapolated to cover the full time range as specified in the range vector selector, so that it is possible to get a non-integer result even if a counter increases only by integer increments.",
   "gridPos": { "h": 2, "w": 6, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(irate(django_http_requests_total_by_transport_total{service=~\"^$service$\"}[30s]))"
    }
   ]
  },
  {
   "title": "Cache hits (%)",
   "type": "stat",
   "gridPos": { "h": 2, "w": 6, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(rate(django_cache_get_hits_total[15m])) / sum(rate(django_cache_get_total[15m])) * 100"
    }
   ]
  },
  {
   "title": "2XX Responses",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(irate(django_http_responses_total_by_status_total{status=~\"2.+\",service=~\"^$service$\"}[30s]))"
    }
   ]
  },
  {
   "title": "4XX Responses",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(irate(django_http_responses_total_by_status_total{status=~\"4.+\",service=~\"^$service$\"}[30s]))"
    }
   ]
  },
  {
   "title": "5XX Responses",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 20, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(irate(django_http_responses_total_by_status_total{status=~\"5.+\",service=~\"^$service$\"}[30s]))"
    }
   ]
  },
  {
   "title": "Requests",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 2 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(irate(django_http_requests_total_by_view_transport_method_total{service=~\"^$service$\",view!~\"prometheus-django-metrics|healthcheck\"}[30s])) by(method, view)",
     "legendFormat": "{{method}} /{{view}}"
    }
   ]
  },
  {
   "title": "Request Latency",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 2 },
   "yaxes": [
    { "format": "dtdurations" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.50, sum(rate(django_http_requests_latency_seconds_by_view_method_bucket{service=~\"^$service$\",view!~\"prometheus-django-metrics|healthcheck\"}[5m])) by (job, le))",
     "legendFormat": "quantile=50"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(django_http_requests_latency_seconds_by_view_method_bucket{service=~\"^$service$\",view!~\"prometheus-django-metrics|healthcheck\"}[5m])) by (job, le))",
     "legendFormat": "quantile=95"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(django_http_requests_latency_seconds_by_view_method_bucket{service=~\"^$service$\",view!~\"prometheus-django-metrics|healthcheck\"}[5m])) by (job, le))",
     "legendFormat": "quantile=99"
    },
    {
     "expr": "histogram_quantile(0.999, sum(rate(django_http_requests_latency_seconds_by_view_method_bucket{service=~\"^$service$\",view!~\"prometheus-django-metrics|healthcheck\"}[5m])) by (job, le))",
     "legendFormat": "quantile=99.9"
    }
   ]
  },
  {
   "title": "Slow requests (>=601 ms)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 11 },
   "targets": [
    {
     "expr": "django_http_requests_latency_seconds_by_view_method_bucket{le=~\"\\\\+Inf|0\\\\.8\", view!=\"<unnamed view>\", view!=\"prometheus-django-metrics\"}",
     "legendFormat": "{{method}} /{{view}}, le: {{le}}"
    }
   ]
  },
  {
   "title": "Response count",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 11 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(irate(django_http_responses_before_middlewares_total{service=~\"^$service$\", view!~\"prometheus-django-metrics|healthcheck\"}[30s])) by(job)",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Database Ops",
   "type": "graph",
   "gridPos": { "h": 9, "w": 6, "x": 0, "y": 20 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(irate(django_db_execute_total{service=~\"^$service$\"}[30s])) by (vendor)",
     "legendFormat": "{{vendor}}"
    }
   ]
  },
  {
   "title": "DB Connections",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 6, "x": 6, "y": 20 },
   "targets": [
    {
     "expr": "django_db_new_connections_total",
     "legendFormat": "DB connections count"
    }
   ]
  },
  {
   "title": "Response Status",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 20 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(irate(django_http_responses_total_by_status_total{service=~\"^$service$\", view!~\"prometheus-django-metrics|healthcheck\"}[30s])) by(status)",
     "legendFormat": "{{status}}"
    }
   ]
  }
 ]
}